import {test,expect} from '@playwright/test';
import {healthView,investigationPayload} from '../src/healthView';
import type {Bootstrap,Evidence,Health} from '../src/types';
const name='Example Product';
const catalog=['Scheduling API','Profile API','Account API'].map(dependent_api=>({product_name:name,dependent_api}));
const r=(id:string,api:string,date:string,value:number):Evidence=>({evidence_id:id,product_name:name,component:api,signal_type:'api_metric',metric_name:'API Error Rate',timestamp:`2026-09-${date}T12:00:00Z`,value,baseline:1});
const health:Health={status:'completed',run_id:'test',scope:{products:[name],start:'2026-09-02',end:'2026-09-08'},report:{summary:'Scheduling issue',products:[{product_name:name,status:'Needs Attention',summary:'Scheduling errors occurred.',evidence_refs:['bad'],limitations:[],issues:[{id:'issue',finding:'Scheduling errors interrupted payments.',date:'2026-09-03',severity:'High',affected_components:['Scheduling API'],evidence_refs:['bad'],recommendation:'Review failed schedules.',investigate:true}]}]},evidence:{bad:r('bad','Scheduling API','03',10.7),recovered:r('recovered','Scheduling API','07',1.1),profile:r('profile','Profile API','08',1),account:r('account','Account API','08',1),complaint:{evidence_id:'complaint',product_name:name,signal_type:'complaint',timestamp:'2026-09-03T12:00:00Z'},prior:{evidence_id:'prior',product_name:name,signal_type:'complaint',timestamp:'2026-09-01T12:00:00Z'},incident:{evidence_id:'incident',product_name:name,component:'Scheduling API',signal_type:'incident',incident_id:'INC-1',timestamp:'2026-09-03T12:00:00Z'}}};
const data:Bootstrap={products:[name],product_catalog:catalog,start:'2026-09-01',end:'2026-09-08',signals:[],runs:[],knowledge:null,reviews:{},drafts:{},approved:{},opportunities:[],explored:{},health,health_reviews:{}};
test('recovery is API-specific and mixed degradation takes precedence',()=>{
 const v=healthView(health.report.products[0],health,data);
 expect(v.apiSummary).toBe('1 recently recovered');expect(v.bucket).toBe('recovered');expect(v.apis.filter(a=>a.status==='healthy')).toHaveLength(2);
 expect(v.apis[0].recovery?.timestamp).toBe('2026-09-07T12:00:00Z');expect(v.apis[0].incidents[0].incident_id).toBe('INC-1');expect(v.priorCount).toBe(1);
 const mixed={...health,evidence:{...health.evidence,account:r('account','Account API','08',8)}};
 const m=healthView(mixed.report.products[0],mixed,data);expect(m.bucket).toBe('attention');expect(m.apiSummary).toBe('1 degraded · 1 recently recovered');
 const missing=structuredClone(health);delete missing.evidence.account;
 expect(healthView(missing.report.products[0],missing,data).apiSummary).toBe('1 recently recovered · 1 without readings');
 const noFinding=structuredClone(health);noFinding.report.products[0].issues=[];
 expect(healthView(noFinding.report.products[0],noFinding,data).apis[0].status).toBe('healthy');
 const outside=structuredClone(health);outside.evidence.bad.timestamp='2026-09-01T12:00:00Z';
 expect(healthView(outside.report.products[0],outside,data).bucket).not.toBe('recovered');
 const context=investigationPayload(v,health).context as Record<string,unknown>;
 expect(context.timeframe).toEqual({start:'2026-09-02',end:'2026-09-08'});expect(context.affected_apis).toEqual(['Scheduling API']);expect(context.complaints).toHaveLength(1);expect(context.incidents).toHaveLength(1);expect(context.metrics).toHaveLength(4);
});
for(const width of [1440,390])test(`multi-API detail and investigation handoff at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:950});
 await page.route('**/api/bootstrap',route=>route.fulfill({json:data}));
 let payload:any;
 await page.route('**/api/jobs',route=>{payload=route.request().postDataJSON();return route.fulfill({json:{id:'investigate'}})});
 await page.route('**/api/jobs/investigate',route=>route.fulfill({json:{status:'running'}}));
 await page.goto('/');
 const card=page.getByRole('article');
 await expect(card).toContainText('3 dependent APIs · 1 recently recovered');
 await expect(card.getByText('API Error Rate',{exact:true})).toHaveCount(0);
 await expect(card).toContainText('Scheduling API · peak error rate 10.7%');
 await card.getByRole('button',{name:name,exact:true}).click();
 const dialog=page.getByRole('dialog');
 await expect(dialog.getByRole('heading',{name:'Dependent APIs (3)'})).toBeVisible();
 for(const api of catalog)await expect(dialog.getByRole('heading',{name:api.dependent_api,exact:true})).toBeVisible();
 await expect(dialog).toContainText('Recovery first observed');
 await page.screenshot({path:`/tmp/pulse-api-detail-${width}.png`,fullPage:true});
 await page.keyboard.press('Escape');
 await page.screenshot({path:`/tmp/pulse-api-health-${width}.png`,fullPage:true});
 await expect(page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).resolves.toBeTruthy();
 await card.getByRole('button',{name:'Investigate finding',exact:true}).click();
 await expect.poll(()=>payload?.context?.affected_apis).toEqual(['Scheduling API']);
 expect(payload.context.timeframe).toEqual({start:'2026-09-02',end:'2026-09-08'});
 expect(payload.context.metrics).toHaveLength(4);
});

test('latest and issue readings keep their values and dates on both views',async({page})=>{
 const scan=structuredClone(health);
 const p=scan.report.products[0];
 p.issues[0].date='2026-09-06';p.issues[0].evidence_refs.push('product-low');
 scan.evidence['product-low']={evidence_id:'product-low',product_name:name,component:'Scheduling',signal_type:'product_metric',metric_name:'Scheduling Success Rate',timestamp:'2026-09-06T12:00:00Z',value:80.6,baseline:95};
 scan.evidence['product-latest']={...scan.evidence['product-low'],evidence_id:'product-latest',timestamp:'2026-09-07T12:00:00Z',value:94.8};
 await page.route('**/api/bootstrap',route=>route.fulfill({json:{...data,health:scan}}));
 await page.goto('/');
 const card=page.getByRole('article');
 await expect(card.getByText('Latest: 94.8% · Sep 7',{exact:true})).toBeVisible();
 await expect(card.getByText('At issue: 80.6% · Sep 6',{exact:true})).toBeVisible();
 await card.getByRole('button',{name:name,exact:true}).click();
 const readings=page.getByRole('region',{name:'Product metric readings'});
 await expect(readings.getByText('Latest: 94.8% · Sep 7',{exact:true})).toBeVisible();
 await expect(readings.getByText('At issue: 80.6% · Sep 6',{exact:true})).toBeVisible();
 await expect(readings).toContainText('Baseline 95% · -0.2 pts');
 await expect(readings).toContainText('Baseline 95% · -14.4 pts');
 await readings.getByRole('button',{name:'View issue reading',exact:true}).click();
 await expect(page.getByRole('dialog',{name:'Supporting evidence'})).toContainText('80.6%');
 const missing=structuredClone(scan);delete missing.evidence['product-low'];
 expect(healthView(missing.report.products[0],missing,data).atIssue).toBeUndefined();
});
