import {test,expect} from '@playwright/test';
import knowledge from './knowledge.json' with {type:'json'};
test('knowledge review, confirmation, draft and source navigation',async({page})=>{
 let compared=false;let confirmed=false;let drafted=false;
 const gap=knowledge.gaps[0];
 const draft={proposed_wording:'Verify the bank account before using it for payment.',reason:'Align the procedure with the authoritative verification requirement.',truth_ref:gap.truth_ref};
 await page.route('**/api/bootstrap',async route=>{const response=await route.fetch();const data=await response.json();await route.fulfill({json:{...data,knowledge:compared?knowledge:null,reviews:confirmed?{[gap.id]:'Confirmed'}:{},drafts:drafted?{[gap.id]:draft}:{}}})});
 await page.route('**/api/jobs',async route=>{const payload=route.request().postDataJSON();if(payload.kind==='knowledge')compared=true;if(payload.kind==='draft')drafted=true;await route.fulfill({json:{id:payload.kind}})});
 await page.route('**/api/jobs/*',async route=>{await route.fulfill({json:{id:'test',status:'completed',result:route.request().url().endsWith('draft')?draft:knowledge}})});
 await page.route('**/api/gaps/*/review',async route=>{confirmed=true;await route.fulfill({json:{decision:'Confirmed'}})});
 await page.route('**/api/gaps/*/approve',async route=>{await route.fulfill({json:{preview:'Approved update'}})});
 await page.goto('/');await expect(page.getByRole('heading',{name:'What needs your attention?'})).toBeVisible();
 await page.getByRole('button',{name:'Knowledge Health',exact:true}).click();
 await page.getByLabel('Product',{exact:true}).selectOption('Bank Account Management');
 await expect(page.getByRole('heading',{name:'Ready to check your guidance'})).toBeVisible();
 await page.getByRole('button',{name:'Check Knowledge Consistency',exact:true}).click();
 await expect(page.getByText(gap.title,{exact:true})).toBeVisible();
 await page.screenshot({path:'/tmp/pulse-react-knowledge.png',fullPage:true});
 await page.getByText(gap.title,{exact:true}).click();
 const dialog=page.getByRole('dialog');await expect(dialog.getByRole('button',{name:'Draft Update',exact:true})).toBeDisabled();
 await dialog.getByRole('button',{name:'Confirm Gap',exact:true}).click();
 await expect(dialog.getByRole('button',{name:'Draft Update',exact:true})).toBeEnabled();
 await dialog.getByRole('button',{name:'Draft Update',exact:true}).click();
 await expect(dialog.getByLabel('Proposed replacement wording')).toHaveValue(draft.proposed_wording);
 await expect(dialog.getByRole('button',{name:'Download approved request'})).toBeDisabled();
 await dialog.getByRole('button',{name:'Approve wording'}).click();
 await expect(dialog.getByRole('button',{name:'Download approved request'})).toBeEnabled();
 await dialog.getByLabel('Proposed replacement wording').fill('Edited wording');
 await expect(dialog.getByRole('button',{name:'Download approved request'})).toBeDisabled();
 await dialog.getByRole('button',{name:'View source',exact:true}).first().click();
 await expect(page.getByRole('dialog',{name:'Supporting evidence'})).toBeVisible();
 await page.keyboard.press('Escape');await expect(page.getByRole('dialog',{name:'Review knowledge gap'})).toBeVisible();
 await page.screenshot({path:'/tmp/pulse-react-gap.png',fullPage:true});
});
test('comparison errors give a retry and never imply no gaps',async({page})=>{
 await page.route('**/api/jobs',r=>r.fulfill({json:{id:'failed'}}));
 await page.route('**/api/jobs/failed',r=>r.fulfill({json:{status:'completed',result:{status:'validation_failed',error:'A quotation could not be verified. Retry the comparison.'}}}));
 await page.goto('/#knowledge');await page.getByRole('button',{name:'Check Knowledge Consistency'}).click();
 await expect(page.getByRole('alert')).toContainText('quotation could not be verified');
 await expect(page.getByRole('button',{name:'Retry',exact:true})).toBeEnabled();
 await expect(page.getByText('No gaps found in this review')).toHaveCount(0);
});
test('mobile navigation and accessible investigation form',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/#investigations');
 await page.getByRole('button',{name:'New investigation',exact:true}).click();
 await expect(page.getByRole('dialog',{name:'New investigation'})).toBeVisible();
 await page.getByLabel('Complaint or issue').fill('Verification failed');await page.getByLabel('Customer ID').fill('C1001');
 await expect(page.getByRole('button',{name:'Investigate',exact:true})).toBeEnabled();
 await expect(page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).resolves.toBeTruthy();
 await page.screenshot({path:'/tmp/pulse-react-mobile.png',fullPage:true});
 await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);
});
