import {useEffect,useRef,useState,type FormEvent,type ReactNode} from 'react';
import {Activity,ArrowRight,ArrowUpRight,BookOpen,Check,ChevronRight,Compass,FileText,Layers,LoaderCircle,MessageSquare,Plus,RefreshCw,Search,ShieldCheck,Sparkles,TriangleAlert,User} from 'lucide-react';
import {api} from './api';
import {Badge,Drawer,Empty,EvidenceCard,EvidenceList,Metric,Raw,Stepper,Timeline,docName,short,when,Quote,MarkdownText} from './components';
import type {Bootstrap,Draft,Evidence,Gap,Health,Issue,Job,JobPayload,Knowledge,Page,Pattern,Run} from './types';
const nav=[{id:'health',label:'Product Health',icon:Activity},{id:'investigations',label:'Investigations',icon:Search},{id:'knowledge',label:'Knowledge Health',icon:BookOpen},{id:'opportunities',label:'Opportunities',icon:Compass}] as const;
const severityTone={High:'critical',Medium:'warning',Low:'neutral'} as const;
const severityOrder={High:0,Medium:1,Low:2} as const;
const classificationTone:Record<string,'neutral'|'warning'|'good'|'critical'>={'Technical / Service Issue':'critical','Customer Experience Issue':'warning','Knowledge / Documentation Issue':'warning','Expected Product Behavior':'good','Insufficient Evidence':'neutral'};
function notableEvent(events:Evidence[]){return events.length?events.find(e=>/fail|error|abandon|declin|cancel/i.test(e.result||''))||events[events.length-1]:undefined}
function leadMetric(metrics:Evidence[]){return metrics.length?[...metrics].sort((a,b)=>Math.abs((b.value??0)-(b.baseline??0))-Math.abs((a.value??0)-(a.baseline??0)))[0]:undefined}
function journeyObservation(events:Evidence[]){
 if(!events.length)return ''
 const badIndex=events.findIndex(e=>/fail|error|abandon|declin|cancel/i.test(e.result||''))
 if(badIndex===-1)return `The customer completed all ${events.length} recorded step${events.length===1?'':'s'} without an observed failure.`
 return `The customer progressed through ${badIndex} step${badIndex===1?'':'s'} normally, then ${(events[badIndex].action||'the next step').toLowerCase()} ${(events[badIndex].result||'failed').toLowerCase()}.`
}
const titles={health:['What needs your attention?','Understand product health. Decide where to look next.'],investigations:['Follow the evidence','Investigate a customer complaint or an issue from product health.'],knowledge:['Keep your product knowledge aligned','Compare guidance with your Product Source of Truth.'],opportunities:['See the patterns worth exploring','Turn repeated customer friction into questions worth pursuing.']};
type Detail={type:'issue';product:string;issue:Issue;scan:Health}|{type:'run';run:Run}|{type:'gap';gap:Gap}|{type:'pattern';pattern:Pattern}|{type:'new'};
export default function App(){
 const [page,setPage]=useState<Page>(()=>(nav.some(n=>n.id===location.hash.slice(1))?location.hash.slice(1):'health') as Page);
 const [data,setData]=useState<Bootstrap|null>(null),[product,setProduct]=useState('All products'),[start,setStart]=useState(''),[end,setEnd]=useState('');
 const [health,setHealth]=useState<Record<string,Health>>({}),[detail,setDetail]=useState<Detail|null>(null),[source,setSource]=useState<Evidence|null>(null),[sourceText,setSourceText]=useState('');
 const [busy,setBusy]=useState<{id:string;payload:JobPayload;step?:string|null}|null>(null),[error,setError]=useState(''),[lastRequest,setLastRequest]=useState<JobPayload|null>(null);
 const [notice,setNotice]=useState(''),[notes,setNotes]=useState(''),[wording,setWording]=useState(''),[approved,setApproved]=useState(''),[tab,setTab]=useState('Key evidence');
 const initial=useRef(true);const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);const boot=()=>api<Bootstrap>('/bootstrap').then(d=>{setData(d);if(initial.current){setStart(d.start);setEnd(d.end);initial.current=false}return d});
 useEffect(()=>{boot().catch(e=>setError(e.message));return()=>clearTimeout(timer.current)},[]);
 useEffect(()=>{const changed=()=>{const next=location.hash.slice(1);if(nav.some(n=>n.id===next)){setPage(next as Page);setDetail(null);setSource(null)}};window.addEventListener('hashchange',changed);return()=>window.removeEventListener('hashchange',changed)},[]);
 const go=(p:Page)=>{setPage(p);location.hash=p;setDetail(null);setSource(null);setError('');setNotice('')};
 const scoped=product==='All products'?data?.products||[]:[product];const key=JSON.stringify([scoped,start,end]);const scan=health[key];
 const knowledge=data?.knowledge;const knowledgeMatches=knowledge&&scoped.every(p=>knowledge.scope.products.includes(p));
 const gaps=knowledgeMatches?knowledge!.gaps.filter(g=>scoped.includes(g.product)):[];
 const selectedGap=detail?.type==='gap'?detail.gap:null;const draft=selectedGap?data?.drafts[selectedGap.id]:undefined;const gapReview=selectedGap?data?.reviews[selectedGap.id]:undefined;
 const show=(d:Detail)=>{setDetail(d);setNotes(d.type==='run'?d.run.notes:'');setTab('Key evidence');setApproved('');if(d.type==='gap')setWording(data?.drafts[d.gap.id]?.proposed_wording||'')};
 const viewSource=(r:Evidence)=>{setSource(r);setSourceText('');const name=(r.metadata?.source||r.source||'').split('/').pop();if(name)api<{text:string}>('/documents/'+encodeURIComponent(name)).then(d=>setSourceText(d.text)).catch(()=>setSourceText('Source document unavailable.'))};
 async function launch(payload:JobPayload){
  if(busy)return;setError('');setNotice('');setLastRequest(payload);
  try{const {id}=await api<{id:string}>('/jobs',payload);setBusy({id,payload});
   const poll=async()=>{try{const job=await api<Job>('/jobs/'+id);if(job.status==='running'){setBusy(b=>b?{...b,step:job.step}:b);timer.current=setTimeout(poll,1200);return}setBusy(null);if(job.status==='failed'){setError(job.error||'The review could not complete.');return}
    const result=job.result as Health|Knowledge|Run|Draft;
    if('status' in result&&result.status!=='completed'){setError(result.error||'Evidence could not be verified. No finding has been approved.');return}
    if(payload.kind==='health')setHealth(h=>({...h,[JSON.stringify([payload.products,payload.start,payload.end])]:result as Health}));
    const d=await boot();
    if(payload.kind==='investigation'){setPage('investigations');history.replaceState(null,'','#investigations');show({type:'run',run:result as Run})}
    if(payload.kind==='draft'){setWording((result as Draft).proposed_wording);setApproved('');setTimeout(()=>document.getElementById('draft-editor')?.scrollIntoView({behavior:'smooth'}),100)}
    if(payload.kind==='knowledge'){setDetail(null);setNotice(`Comparison complete. ${d.knowledge?.gaps.length||0} potential ${(d.knowledge?.gaps.length||0)===1?'gap is':'gaps are'} ready to review.`)}
   }catch(e){setBusy(null);setError((e as Error).message)}};await poll();
  }catch(e){setBusy(null);setError((e as Error).message)}
 }
 async function reviewRun(decision:string){if(detail?.type!=='run')return;try{const run=await api<Run>(`/investigations/${detail.run.id}/review`,{decision,notes});setDetail({type:'run',run});await boot();setNotice('Review saved. No customer or product changes were made.')}catch(e){setError((e as Error).message)}}
 async function reviewGap(decision:string){if(!selectedGap)return;try{await api(`/gaps/${selectedGap.id}/review`,{decision});setApproved('');if(decision==='Not a gap'){setDetail(null);setWording('')}await boot()}catch(e){setError((e as Error).message)}}
 async function approveUpdate(download=false){if(!selectedGap)return;try{const {preview}=await api<{preview:string}>(`/gaps/${selectedGap.id}/${download?'export':'approve'}`,{wording});if(download){const url=URL.createObjectURL(new Blob([preview],{type:'text/markdown'}));const a=document.createElement('a');a.href=url;a.download='documentation-update-request.md';a.click();URL.revokeObjectURL(url)}else setApproved(wording)}catch(e){setError((e as Error).message)}}
 const patternId=(p:Pattern)=>p.product+'-'+p.pattern;
 const counts:Record<Page,number>={health:data?.signals.length||0,investigations:data?.runs.filter(r=>r.review==='Pending review').length||0,knowledge:data?.knowledge?data.knowledge.gaps.filter(g=>!data.reviews[g.id]).length:0,opportunities:data?data.opportunities.filter(p=>!data.explored[patternId(p)]).length:0};
 const presetStart=(days:number)=>{const d=new Date(data!.end);d.setDate(d.getDate()-(days-1));const iso=d.toISOString().slice(0,10);return iso<data!.start?data!.start:iso};
 const datePresets=[{label:'Last 7 days',start:()=>presetStart(7)},{label:'Last 30 days',start:()=>presetStart(30)},{label:'All time',start:()=>data!.start}];
 const banners=<>{error&&<div role="alert" className="mb-5 flex flex-wrap items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><TriangleAlert size={19} className="shrink-0"/><div className="flex-1"><p className="font-semibold">We couldn’t complete that action</p><p className="mt-1 leading-6">{error}</p></div><button className="secondary" disabled={!!busy} onClick={()=>lastRequest?launch(lastRequest):boot().then(()=>setError('')).catch(e=>setError(e.message))}><RefreshCw size={14}/>Retry</button></div>}{busy&&<div role="status" className="mb-5 flex items-center gap-3 rounded-xl border border-pulse-100 bg-pulse-50 p-4 text-sm text-pulse-700"><LoaderCircle className="animate-spin" size={18}/><div><p className="font-semibold">{busy.payload.kind==='health'?'Reviewing product health':busy.payload.kind==='knowledge'?'Comparing product guidance':busy.payload.kind==='draft'?'Drafting your update':'Investigating the evidence'}…</p><p className="mt-1 text-xs">{busy.step?busy.step+'…':'You can browse other pages while this finishes.'}</p></div></div>}{notice&&<div role="status" className="mb-5 flex gap-2 text-sm text-pulse-700"><Check size={16}/>{notice}</div>}</>;
 return <div className="min-h-screen lg:flex"><aside className="border-b border-slate-200 bg-white px-5 py-5 lg:fixed lg:inset-y-0 lg:w-60 lg:border-r lg:py-8"><a href="#health" onClick={()=>go('health')} className="flex items-center gap-3 text-lg font-bold tracking-tight"><span className="rounded-xl bg-pulse-700 p-2 text-white"><Layers size={22}/></span>Product Pulse</a><p className="eyebrow mt-9 hidden lg:block">Your workspace</p><nav aria-label="Main navigation" className="mt-3 flex gap-1 overflow-x-auto lg:flex-col">{nav.map(({id,label,icon:Icon})=><button key={id} aria-current={page===id?'page':undefined} onClick={()=>go(id)} className={'flex shrink-0 items-center justify-between gap-3 rounded-xl px-3 py-3 text-sm font-medium '+(page===id?'bg-pulse-50 text-pulse-700':'text-slate-500 hover:bg-slate-50')}><span className="flex items-center gap-3"><Icon size={18}/>{label}</span>{!!counts[id]&&<span className="rounded-full bg-pulse-600 px-1.5 py-0.5 text-[10px] font-bold text-white">{counts[id]}</span>}</button>)}</nav><div className="mt-8 hidden rounded-2xl border border-pulse-100 bg-pulse-50 p-4 lg:absolute lg:bottom-8 lg:left-5 lg:right-5 lg:block"><ShieldCheck size={20} className="mb-3 text-pulse-700"/><p className="text-sm font-semibold text-pulse-700">AI investigates.<br/>PM decides.</p><p className="mt-2 text-xs leading-5 text-slate-500">Your judgment comes first.<br/>Nothing is published automatically.</p></div></aside>
 <main className="min-w-0 flex-1 lg:ml-60"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200/70 bg-white/80 px-6 py-4 lg:px-10"><div className="flex items-center gap-2 text-sm text-slate-400">Workspace<ChevronRight size={14}/><span className="text-slate-700">{nav.find(n=>n.id===page)?.label}</span></div><div className="flex items-center gap-3"><span className="hidden text-xs text-slate-400 sm:block">Synthetic demo data</span><label className="sr-only" htmlFor="global-product">Product</label><select id="global-product" value={product} onChange={e=>{setProduct(e.target.value);setDetail(null)}}><option>All products</option>{data?.products.map(p=><option key={p}>{p}</option>)}</select></div></header>
 <div className="mx-auto max-w-6xl px-5 py-8 sm:px-8 lg:px-10"><div className="mb-7 flex flex-wrap items-start justify-between gap-5"><div><p className="eyebrow mb-2">{nav.find(n=>n.id===page)?.label}</p><h1 className="page-title">{titles[page][0]}</h1><p className="muted mt-2">{titles[page][1]}</p></div>{page==='health'&&<button className="primary" disabled={!!busy||!data} onClick={()=>launch({kind:'health',products:scoped,start,end})}><Sparkles size={16}/>Run Health Scan</button>}{page==='knowledge'&&<button className="primary" disabled={!!busy||!data} onClick={()=>launch({kind:'knowledge',products:scoped})}><Sparkles size={16}/>Check Knowledge Consistency</button>}{page==='investigations'&&<button className="primary" disabled={!!busy||!data} onClick={()=>show({type:'new'})}><Plus size={16}/>New investigation</button>}</div>{banners}
 {!data&&!error&&<Empty title="Opening your workspace"><LoaderCircle className="mx-auto animate-spin"/></Empty>}
 {data&&page==='health'&&<><div className="mb-6 flex flex-wrap items-center gap-3 text-sm"><span className="text-slate-500">Review period</span><input aria-label="Review start date" type="date" min={data.start} max={data.end} value={start} onChange={e=>setStart(e.target.value)}/><span className="text-slate-400">to</span><input aria-label="Review end date" type="date" min={start} max={data.end} value={end} onChange={e=>setEnd(e.target.value)}/><div className="flex gap-1.5">{datePresets.map(p=><button key={p.label} type="button" className="rounded-lg border border-slate-200 bg-white px-2.5 py-1 text-xs font-medium text-slate-600 hover:bg-slate-50" onClick={()=>{setStart(p.start());setEnd(data.end)}}>{p.label}</button>)}</div></div>
 {scan?<div className="space-y-4">{scan.report.products.map(p=><section className="card" key={p.product_name}><div className="mb-4 flex items-center justify-between gap-3"><h2 className="text-lg font-semibold">{p.product_name}</h2><Badge tone={p.status==='Needs Attention'?'warning':'good'}>{p.status}</Badge></div>{p.issues.length?[...p.issues].sort((a,b)=>severityOrder[a.severity as keyof typeof severityOrder]-severityOrder[b.severity as keyof typeof severityOrder]).map((issue,i)=><div key={i} className="flex flex-col justify-between gap-4 border-t border-slate-100 py-4 last:pb-0 sm:flex-row sm:items-center"><div><Badge tone={severityTone[issue.severity as keyof typeof severityTone]}>{issue.severity}</Badge><p className="mt-2 font-medium">{short(issue.finding,140)}</p><p className="muted mt-1">{issue.affected_components.join(', ')} · {issue.date}</p><p className="mt-2 text-xs text-slate-400">{issue.evidence_refs.length} supporting references · {issue.investigate?'Investigation recommended':'Review suggested'}</p></div><button className="secondary shrink-0" onClick={()=>show({type:'issue',product:p.product_name,issue,scan})}>Review finding<ArrowRight size={15}/></button></div>):<p className="muted">{short(p.summary,180)}</p>}</section>)}</div>:<><div className="mb-5 rounded-xl border border-pulse-100 bg-pulse-50 px-5 py-4"><p className="text-sm font-semibold text-pulse-700">Start with a health scan</p><p className="muted">Get an assessed brief across your products. The signals below are preliminary observations from the sample data.</p></div><div className="space-y-3">{data.signals.filter(s=>scoped.includes(s.product)&&s.day>=start&&s.day<=end).map(signal=><article key={signal.id} className="card flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><Badge tone="warning">Preliminary signal</Badge><h2 className="mt-3 text-base font-semibold">{signal.title}</h2><p className="muted mt-1">{signal.product} · {signal.day}</p></div><button className="secondary shrink-0" disabled={!!busy} onClick={()=>launch({kind:'investigation',product:signal.product,complaint:signal.title,day:signal.day,context:{origin:'Supporting signal',finding:signal.detail}})}>Investigate<ArrowRight size={15}/></button></article>)}</div></>}
 </>}
 {data&&page==='investigations'&&<>{data.runs.filter(r=>scoped.includes(r.product)).length?<div className="space-y-3">{[...data.runs].reverse().filter(r=>scoped.includes(r.product)).map(run=><button key={run.id} className="card flex w-full items-center justify-between gap-4 text-left hover:border-pulse-600" onClick={()=>show({type:'run',run})}><div><Badge tone={run.status==='completed'?(classificationTone[run.classification]||'neutral'):'neutral'}>{run.status==='completed'?run.classification:'Incomplete review'}</Badge><h2 className="mt-3 text-base font-semibold">{short(run.complaint,120)}</h2><p className="muted mt-1">{run.product} · {run.customer||'Product issue'} · {run.day}</p></div><span className="hidden text-xs text-slate-500 sm:block">{run.review}</span><ChevronRight className="shrink-0 text-slate-400" size={20}/></button>)}</div>:<Empty title="Start with a customer question" icon={<MessageSquare size={25}/>}><p>Describe an issue, or investigate a signal from Product Health. Your findings and review history will appear here.</p><button className="link mt-4" onClick={()=>show({type:'new'})}>Start an investigation<ArrowRight size={14}/></button></Empty>}</>}
 {data&&page==='knowledge'&&<><div className="mb-6 flex flex-wrap items-center gap-4 rounded-2xl border border-slate-200 bg-white p-5"><span className="rounded-xl bg-pulse-50 p-3 text-pulse-700"><ShieldCheck size={23}/></span><div className="flex-1"><p className="text-sm font-semibold">Product Source of Truth</p><p className="muted">The authority for product rules and expected behavior.</p></div><button className="link" onClick={()=>viewSource({source:'data/product_source_of_truth.md',text:'Authoritative product rules'})}>View source<ArrowUpRight size={14}/></button></div>
 {knowledgeMatches?<><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-semibold">Potential gaps to review</h2><span className="text-xs text-slate-400">{gaps.length} in selected products</span></div>{gaps.length?<div className="space-y-3">{gaps.map(gap=><button key={gap.id} className="card flex w-full items-center justify-between gap-4 text-left hover:border-pulse-600" onClick={()=>show({type:'gap',gap})}><div><Badge tone={data.reviews[gap.id]==='Confirmed'?'good':data.reviews[gap.id]==='Not a gap'?'neutral':'warning'}>{data.reviews[gap.id]||'Needs review'}</Badge><h2 className="mt-3 text-base font-semibold">{gap.title}</h2><p className="muted mt-1">{gap.product} · {docName(gap.file)}</p></div><span className="link shrink-0">Review gap<ArrowRight size={15}/></span></button>)}</div>:<Empty title="No gaps found in this review" icon={<Check size={24}/>}><p>This is an AI comparison, not a guarantee of complete consistency. Review the scope before deciding.</p></Empty>}<details className="muted mt-5"><summary>What was reviewed?</summary>{knowledge?.report.coverage_notes.map((n,i)=><p className="mt-2" key={i}>{n}</p>)}</details></>:<Empty title={error?'Your comparison needs another attempt':'Ready to check your guidance'} icon={<BookOpen size={25}/>}><p>Compare API Documentation, Agent Procedures and FAQ against the Source of Truth. Review potential gaps before drafting any changes.</p><p className="mt-4 text-xs">1. Compare guidance → 2. Review gaps → 3. Approve an update</p></Empty>}
 <div className="mt-7 grid gap-3 sm:grid-cols-3">{['api_documentation.md','agent_procedures.md','product_faq.md'].map(name=><button key={name} className="card flex items-center gap-3 text-left text-sm text-slate-600" onClick={()=>viewSource({source:'data/'+name,text:'Downstream product guidance'})}><FileText size={18} className="text-slate-400"/>{docName(name)}<ArrowUpRight className="ml-auto" size={14}/></button>)}</div></>}
 {data&&page==='opportunities'&&<>{data.opportunities.filter(p=>scoped.includes(p.product)).length?<div className="space-y-4">{data.opportunities.filter(p=>scoped.includes(p.product)).map(p=><article key={patternId(p)} className="card"><Badge>Emerging pattern</Badge><h2 className="mt-3 text-lg font-semibold">{p.pattern.replaceAll('_',' ').toLowerCase()}</h2><p className="muted mt-1">{p.product} · {p.sessions.length} sessions across {p.runs.length} investigations</p><p className="my-4 text-sm text-slate-600">Repeated friction at the same step may be worth exploring.</p><button className="link" onClick={()=>{show({type:'pattern',pattern:p});setNotes(data.explored[patternId(p)]||'')}}>Explore opportunity<ArrowRight size={15}/></button></article>)}</div>:<Empty title="Patterns emerge as you investigate" icon={<Compass size={25}/>}><p>Related customer experiences will appear here after investigations uncover repeated responses. These are opportunities to explore—not roadmap decisions.</p><button className="link mt-4" onClick={()=>go('investigations')}>Go to investigations<ArrowRight size={14}/></button></Empty>}</>}
 <footer className="mt-12 border-t border-slate-200/70 pt-4 text-xs text-slate-400">AI-powered product intelligence for Product Managers · Reviews run only when requested.</footer></div></main>
 {detail&&!source&&<Drawer title={detail.type==='new'?'New investigation':detail.type==='gap'?'Review knowledge gap':detail.type==='pattern'?'Explore opportunity':'Review finding'} onClose={()=>setDetail(null)}>{banners}
 {detail.type==='new'&&<InvestigationForm products={data?.products||[]} selected={product} day={data?.start||''} busy={!!busy} onSubmit={launch}/>}
 {detail.type==='issue'&&<><Badge tone={severityTone[detail.issue.severity as keyof typeof severityTone]}>{detail.issue.severity} · Needs attention</Badge><h2 className="text-2xl font-semibold">{detail.issue.finding}</h2><p className="muted">{detail.product} · {detail.issue.date}</p><h3 className="font-semibold">Why this needs attention</h3><EvidenceList records={detail.issue.evidence_refs.map(r=>detail.scan.evidence[r]).filter(Boolean)} onView={viewSource}/><section className="card border-pulse-100 bg-pulse-50"><p className="eyebrow text-pulse-700">Recommendation</p><p className="mt-2 text-sm leading-6">{detail.issue.recommendation}</p></section><button className="primary" disabled={!!busy} onClick={()=>launch({kind:'investigation',product:detail.product,complaint:detail.issue.finding,day:detail.issue.date,context:{origin:'Product Health',issue:detail.issue}})}>Investigate<ArrowRight size={16}/></button></>}
 {detail.type==='run'&&<RunReview run={detail.run} notes={notes} setNotes={setNotes} busy={!!busy} tab={tab} setTab={setTab} viewSource={viewSource} reviewRun={reviewRun} launch={launch}/>}
 {selectedGap&&<><Stepper step={draft?2:gapReview==='Confirmed'?1:0}/><Badge tone={gapReview==='Confirmed'?'good':'warning'}>{gapReview||'Needs your review'}</Badge><h2 className="text-2xl font-semibold">{selectedGap.title}</h2><p className="muted">{selectedGap.product} · {selectedGap.kind}</p><div className="grid gap-4 sm:grid-cols-2"><section className="card border-pulse-100"><p className="eyebrow text-pulse-700">Source of Truth</p><div className="mt-3"><Quote text={selectedGap.truth_evidence.text}/></div><button className="link mt-4 text-xs" onClick={()=>viewSource(selectedGap.truth_evidence)}>View source<ArrowUpRight size={13}/></button></section><section className="card"><p className="eyebrow">{docName(selectedGap.file)}</p><div className="mt-3"><Quote text={selectedGap.current_evidence.text}/></div><button className="link mt-4 text-xs" onClick={()=>viewSource(selectedGap.current_evidence)}>View source<ArrowUpRight size={13}/></button></section></div><div><h3 className="font-semibold">Why it may be inconsistent</h3><p className="muted mt-2">{selectedGap.why}</p></div><p className="text-sm text-slate-600">Confirm whether this is a real gap before drafting replacement guidance.</p><div className="flex flex-wrap gap-2"><button className="secondary" disabled={!!busy} onClick={()=>reviewGap('Not a gap')}>Not a Gap</button><button className={gapReview==='Confirmed'?'secondary':'primary'} disabled={!!busy||gapReview==='Confirmed'} onClick={()=>reviewGap('Confirmed')}><Check size={16}/>{gapReview==='Confirmed'?'Gap confirmed':'Confirm Gap'}</button><button className="primary" disabled={!!busy||gapReview!=='Confirmed'} onClick={()=>launch({kind:'draft',gap_id:selectedGap.id})}>Draft Update<ArrowRight size={16}/></button></div>
 {draft&&gapReview==='Confirmed'&&<section id="draft-editor" className="scroll-mt-20 space-y-4 border-t border-slate-200 pt-6"><h3 className="text-lg font-semibold">Review your proposed update</h3><label className="label" htmlFor="wording">Proposed replacement wording</label><textarea id="wording" className="w-full" rows={6} value={wording} onChange={e=>{setWording(e.target.value);setApproved('')}}/><div className="card"><p className="eyebrow">Documentation Update Request</p><p className="mt-3 text-sm font-semibold">{docName(selectedGap.file)}</p><p className="mt-3 whitespace-pre-wrap text-sm leading-6">{wording}</p><p className="muted mt-4">Reason: {draft.reason}</p><p className="mt-3 text-xs text-slate-400">Source of Truth: {draft.truth_ref}</p></div><div className="flex gap-3"><button className="primary" disabled={!wording.trim()||!!busy} onClick={()=>approveUpdate()}>Approve wording</button><button className="secondary" disabled={!approved||approved!==wording||!!busy} onClick={()=>approveUpdate(true)}>Download approved request</button></div><p className="muted">Editing the wording requires a new approval. Downloading does not publish or notify anyone.</p></section>}<Raw data={selectedGap}/></>}
 {detail.type==='pattern'&&<><Badge>Potential opportunity</Badge><h2 className="text-2xl font-semibold">{detail.pattern.pattern.replaceAll('_',' ').toLowerCase()}</h2><p className="muted">{detail.pattern.product} · {detail.pattern.sessions.length} distinct sessions</p><EvidenceList records={Object.values(detail.pattern.evidence)} onView={viewSource}/><p className="text-sm leading-6">Explore whether clearer guidance or recovery support would help at this step. Repeated responses do not establish a root cause or overall prevalence.</p><label htmlFor="exploration" className="label">What would you like to learn?</label><textarea id="exploration" className="w-full" rows={4} value={notes} onChange={e=>setNotes(e.target.value)}/><button className="primary" onClick={async()=>{try{await api('/opportunities/explore',{pattern_id:patternId(detail.pattern),notes});await boot();setNotice('Exploration notes saved.')}catch(e){setError((e as Error).message)}}}>Save exploration notes</button></>}
 </Drawer>}
 {source&&<Drawer title="Supporting evidence" onClose={()=>setSource(null)}><p className="eyebrow">{source.text?docName(source.metadata?.source||source.source):source.signal_type||'Customer activity'}</p><h2 className="text-xl font-semibold">{source.metric_name||source.incident_id||source.action||source.product_name||'Product documentation'}</h2>{source.signal_type?.includes('metric')?<Metric r={source}/>:<MarkdownText text={source.text||source.complaint_text||source.details||source.result||''}/>}<p className="muted">{source.timestamp?when(source.timestamp):''}</p><p className="text-xs text-slate-400">{source.evidence_id||source._evidence?.evidence_id||`${source.metadata?.source||source.source||''} · lines ${source.metadata?.line_start||source.line_start||'—'}–${source.metadata?.line_end||source.line_end||'—'}`}</p>{sourceText&&<details className="muted"><summary>View complete source document</summary><div className="mt-4 rounded-xl border border-slate-200 bg-white p-5"><MarkdownText text={sourceText}/></div></details>}<Raw data={source}/></Drawer>}
 </div>
}
function RunReview({run,notes,setNotes,busy,tab,setTab,viewSource,reviewRun,launch}:{run:Run;notes:string;setNotes:(v:string)=>void;busy:boolean;tab:string;setTab:(t:string)=>void;viewSource:(r:Evidence)=>void;reviewRun:(d:string)=>void;launch:(p:JobPayload)=>void}){
 const notable=notableEvent(run.events),metric=leadMetric(run.metrics),incident=run.incidents[0],doc=run.docs[0];
 const isRate=(name?:string)=>(name||'').toLowerCase().includes('rate');
 const chips=[
  notable&&{icon:<User size={16}/>,label:'Customer Journey',value:notable.action||'Customer activity',caption:notable.result||''},
  metric&&{icon:<Activity size={16}/>,label:'API Health',value:`${metric.value??'—'}${isRate(metric.metric_name)?'%':''}`,caption:`vs ${metric.baseline??'—'}${isRate(metric.metric_name)?'%':''} baseline`},
  incident&&{icon:<TriangleAlert size={16}/>,label:'Incident',value:incident.incident_id||'Incident',caption:incident.severity?incident.severity+' severity':'Related'},
  doc&&{icon:<BookOpen size={16}/>,label:'Product Behavior',value:docName((doc.metadata||doc).source||''),caption:`${run.docs.length} document${run.docs.length===1?'':'s'} reviewed`},
 ].filter(Boolean) as {icon:ReactNode;label:string;value:string;caption:string}[];
 const evidenceCards=[!!notable,!!metric,!!incident,!!doc].filter(Boolean).length;
 return <>
  <Badge tone={classificationTone[run.classification]||'neutral'}>{run.classification}</Badge>
  <h2 className="text-2xl font-semibold leading-snug">{short(run.summary,160)}</h2>
  <p className="muted">{run.product} · {run.day}</p>
  {!!chips.length&&<div><p className="eyebrow mb-2">Why Product Pulse thinks this</p><div className="flex flex-wrap gap-3">{chips.map((c,i)=><div key={i} className="flex min-w-[150px] flex-1 items-start gap-2.5 rounded-xl border border-slate-200 bg-white p-3"><span className="mt-0.5 text-slate-400">{c.icon}</span><div><p className="text-xs font-semibold text-slate-500">{c.label}</p><p className="text-sm font-semibold text-slate-800">{c.value}</p><p className="text-xs text-slate-400">{c.caption}</p></div></div>)}</div></div>}
  {(run.missing_evidence.length>0||run.evidence_conflicts?.length>0)&&<div className="rounded-xl border border-amber-100 bg-amber-50 p-4 text-sm text-amber-900"><p className="mb-2 font-semibold">What remains uncertain</p>{run.missing_evidence.map((m,i)=><p className="mt-1 leading-6" key={i}>{m}</p>)}{run.evidence_conflicts?.map((f,i)=><p key={i}>{f.statement}</p>)}</div>}
  <div className="flex gap-4 overflow-x-auto border-b border-slate-200">{['Key evidence','Customer journey','Documentation'].map(t=><button key={t} onClick={()=>setTab(t)} className={'whitespace-nowrap border-b-2 pb-3 text-sm '+(tab===t?'border-pulse-600 font-semibold text-pulse-700':'border-transparent text-slate-400')}>{t}</button>)}</div>
  {tab==='Key evidence'&&<div className="space-y-3">
   {!!notable&&<div className="rounded-xl border border-slate-200 p-4"><p className="eyebrow">Customer Experience</p><p className="mt-2 text-sm leading-6">{run.events.length} customer session step{run.events.length===1?'':'s'} recorded, ending with {(notable.action||'').toLowerCase()} → {(notable.result||'').toLowerCase()}.</p><button className="link mt-2 text-xs" onClick={()=>setTab('Customer journey')}>View journey<ArrowRight size={13}/></button></div>}
   {!!metric&&<div className="rounded-xl border border-slate-200 p-4"><p className="eyebrow">API Health</p><p className="mt-1 text-sm font-semibold">{metric.metric_name||metric.component||metric.dependent_api}</p><Metric r={metric}/><button className="link mt-2 text-xs" onClick={()=>viewSource(metric)}>View metric<ArrowUpRight size={13}/></button></div>}
   {!!incident&&<div className="rounded-xl border border-slate-200 p-4"><p className="eyebrow">Related Incident</p><p className="mt-2 text-sm leading-6">{incident.incident_id}{incident.severity?` (${incident.severity})`:''} — {short(incident.details||'',140)}</p><button className="link mt-2 text-xs" onClick={()=>viewSource(incident)}>View incident<ArrowUpRight size={13}/></button></div>}
   {!!doc&&<div className="rounded-xl border border-slate-200 p-4"><p className="eyebrow">Expected Product Behavior</p><p className="mt-2 text-sm leading-6">{short(doc.text||'',160)}</p><p className="mt-1 text-xs text-slate-400">Source: {docName((doc.metadata||doc).source||'')}</p><button className="link mt-2 text-xs" onClick={()=>viewSource(doc)}>View source<ArrowUpRight size={13}/></button></div>}
   {!!run.refs.length&&<details className="muted"><summary>View all {run.refs.length} supporting record{run.refs.length===1?'':'s'}</summary><div className="mt-3"><EvidenceList records={run.refs.map(r=>run.evidence[r]).filter(Boolean)} onView={viewSource}/></div></details>}
   {!evidenceCards&&!run.refs.length&&<p className="muted">No supporting evidence returned for this section.</p>}
  </div>}
  {tab==='Customer journey'&&<div className="space-y-4"><Timeline events={run.events} onView={viewSource}/>{!!run.events.length&&<div className="rounded-xl border border-slate-200 p-4"><p className="eyebrow">Agent observation</p><p className="mt-2 text-sm leading-6">{journeyObservation(run.events)}</p>{!!notable&&<button className="link mt-2 text-xs" onClick={()=>viewSource(notable)}>Open full session<ArrowUpRight size={13}/></button>}</div>}</div>}
  {tab==='Documentation'&&<EvidenceList records={run.docs} onView={viewSource}/>}
  {run.summary.length>160&&<div><p className="eyebrow mb-2">Product Pulse Assessment</p><p className="text-sm leading-6 text-slate-700">{run.summary}</p></div>}
  {!!run.recommendation&&<div><p className="eyebrow mb-2">Recommended next step</p><p className="text-sm leading-6 text-slate-700">{run.recommendation}</p><p className="mt-2 text-xs italic text-slate-400">The agent recommends. The PM decides.</p></div>}
  <div><p className="eyebrow mb-3">Does this finding look right?</p><div className="flex flex-wrap gap-2"><button className="primary" disabled={busy||run.status!=='completed'} onClick={()=>reviewRun('Confirmed')}><Check size={16}/>Confirm Finding</button><button className="secondary" disabled={busy||run.status!=='completed'} onClick={()=>launch({kind:'investigation',prior_run_id:run.id,question:notes})}>Investigate Further</button><button className="secondary" disabled={busy||run.status!=='completed'} onClick={()=>reviewRun('Disagreed')}>Disagree</button></div><p className="muted mt-2">{run.review}. Your review does not change products or send a customer response.</p></div>
  <div><label className="label" htmlFor="review-notes">Add context or ask Product Pulse to investigate something else</label><textarea id="review-notes" className="w-full" placeholder="Check whether other customers experienced the same error…" value={notes} onChange={e=>setNotes(e.target.value)} rows={3}/></div>
  <Raw data={run}/>
 </>
}
function InvestigationForm({products,selected,day,busy,onSubmit}:{products:string[];selected:string;day:string;busy:boolean;onSubmit:(p:JobPayload)=>void}){
 const [product,setProduct]=useState(products.includes(selected)?selected:products.includes('Bank Account Management')?'Bank Account Management':products[0]);const [complaint,setComplaint]=useState(''),[customer,setCustomer]=useState(''),[date,setDate]=useState(day),[time,setTime]=useState('');
 function submit(e:FormEvent){e.preventDefault();onSubmit({kind:'investigation',product,complaint,customer,day:date||null,approximate_time:date&&time?time:null})}
 return <form onSubmit={submit} className="space-y-5"><h2 className="text-2xl font-semibold">What would you like to understand?</h2><p className="muted">Describe the customer complaint or product issue. Add a customer ID to reconstruct their journey.</p><div><label className="label" htmlFor="investigate-product">Product</label><select id="investigate-product" className="w-full" value={product} onChange={e=>setProduct(e.target.value)}>{products.map(p=><option key={p}>{p}</option>)}</select></div><div><label className="label" htmlFor="complaint">Complaint or issue</label><textarea id="complaint" className="w-full" rows={4} required placeholder="e.g. My bank verification failed and I couldn’t use my account for a payment." value={complaint} onChange={e=>setComplaint(e.target.value)}/></div><div><label className="label" htmlFor="customer">Customer ID <span className="text-slate-400">(optional)</span></label><input id="customer" className="w-full" placeholder="e.g. C1001" value={customer} onChange={e=>setCustomer(e.target.value)}/></div><div className="grid grid-cols-2 gap-4"><div><label className="label" htmlFor="date">Approximate date</label><input id="date" className="w-full" type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><div><label className="label" htmlFor="time">Time (optional)</label><input id="time" className="w-full" type="time" value={time} onChange={e=>setTime(e.target.value)}/></div></div><button className="primary w-full" disabled={busy||!complaint.trim()} type="submit"><Search size={16}/>Investigate</button><button type="button" className="link text-xs" onClick={()=>{setProduct('Bank Account Management');setCustomer('C1001');setDate('2026-09-03');setTime('09:17');setComplaint('I tried to add my bank account, but verification failed and I could not use it for payment.')}}>Use sample complaint · C1001</button></form>
}
