import {useEffect,useRef,type ReactNode} from 'react';
import {ArrowUpRight,Check,ChevronRight,FileText,MessageSquare,Activity,Clock,AlertTriangle,X} from 'lucide-react';
import type {Evidence} from './types';
export const docName=(name='')=>({'product_source_of_truth.md':'Product Source of Truth','api_documentation.md':'API Documentation','agent_procedures.md':'Agent Procedures','product_faq.md':'FAQ'}[name.split('/').pop()!]||name);
export const short=(s='',n=160)=>s.length>n?s.slice(0,n).replace(/\s\S*$/,'')+'…':s;
export const when=(s?:string)=>s?new Date(s).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'Time not supplied';
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:'neutral'|'warning'|'good'|'critical'}){return <span data-tone={tone} className={'badge '+({neutral:'bg-slate-100 text-slate-600',warning:'bg-amber-50 text-amber-800',good:'bg-emerald-50 text-emerald-800',critical:''}[tone])}><span className="h-1.5 w-1.5 shrink-0 rounded-full bg-current"/>{children}</span>}
export function Empty({title,children,icon}: {title:string;children:ReactNode;icon?:ReactNode}){return <div className="card pulse-empty flex min-h-72 flex-col items-center justify-center text-center"><div className="mb-4 rounded-2xl bg-pulse-50 p-4 text-pulse-700">{icon||<Activity size={24}/>}</div><h2 className="text-xl font-semibold">{title}</h2><div className="muted mt-2 max-w-md">{children}</div></div>}
export function Drawer({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){
 const box=useRef<HTMLDivElement>(null);const close=useRef(onClose);close.current=onClose;
 useEffect(()=>{const prior=document.activeElement as HTMLElement;const before=document.body.style.overflow;document.body.style.overflow='hidden';box.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')close.current();if(e.key==='Tab'){const targets=box.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input,select,textarea,summary,[tabindex="0"]');if(!targets?.length)return;const first=targets[0],last=targets[targets.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===box.current)){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);document.body.style.overflow=before;prior?.focus()}},[]);
 return <div className="fixed inset-0 z-40 bg-slate-900/25" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div ref={box} role="dialog" aria-modal="true" aria-label={title} tabIndex={-1} className="panel"><div className="sticky top-0 z-10 flex items-center justify-between border-b border-slate-200 bg-white px-6 py-4"><span className="text-sm font-semibold">{title}</span><button aria-label="Close detail" className="rounded-lg p-2 hover:bg-slate-100" onClick={onClose}><X size={20}/></button></div><div className="space-y-6 p-6 md:p-8">{children}</div></div></div>
}
export function Raw({data}:{data:unknown}){return <details className="mt-5 text-xs text-slate-400"><summary>Technical details</summary><pre className="mt-3 max-h-80 overflow-auto rounded-xl bg-slate-100 p-4 text-slate-600">{JSON.stringify(data,null,2)}</pre></details>}
export function Metric({r}:{r:Evidence}){const rate=r.metric_name?.toLowerCase().includes('rate');const known=typeof r.value==='number'&&typeof r.baseline==='number';const d=known?r.value!-r.baseline!:0;return <><p className="my-2 text-lg font-semibold">{r.value??'—'}{rate?'%':''} <span className="text-xs font-normal text-slate-400">vs {r.baseline??'—'}{rate?'%':''} baseline</span></p><p className="muted">{known?d===0?'At the supplied baseline.':`${Math.abs(d).toFixed(1)} ${rate?'percentage points':'units'} ${d>0?'above':'below'} baseline.`:'Baseline comparison unavailable.'}</p></>}
export function EvidenceCard({r,onView}:{r:Evidence;onView:(r:Evidence)=>void}){
 const meta=r.metadata||r;const doc=!!r.text;const metric=r.signal_type?.includes('metric');const incident=r.signal_type==='incident';const complaint=r.signal_type==='complaint';const session=!!r.session_id;
 const Icon=doc?FileText:metric?Activity:complaint?MessageSquare:incident?AlertTriangle:Clock;
 const label=doc?docName(meta.source):metric?r.metric_name:incident?`Incident ${r.incident_id}`:complaint?'Customer complaint':session?'Customer activity':'Product context';
 return <div className="rounded-xl border border-slate-200 bg-white p-4"><div className="mb-2 flex items-center gap-2 text-xs font-semibold text-slate-500"><Icon size={15}/>{label}</div>
 {metric?<Metric r={r}/>:<p className="text-sm font-medium leading-6">{short(doc?r.text:complaint?r.complaint_text:incident?r.details:session?`${r.action} → ${r.result?.toLowerCase()}`:r.dependent_api||r.component||r.product_name,160)}</p>}
 <p className="mt-2 text-xs text-slate-400">{doc?'Expected product behavior':incident?`${r.severity||'Unspecified'} severity · ${when(r.timestamp)} · End time not supplied`:`${r.customer_id||r.component||''} · ${when(r.timestamp)}`}</p>
 <button className="link mt-3 text-xs" onClick={()=>onView(r)}>{doc?'View source':'View evidence'}<ArrowUpRight size={13}/></button></div>
}
export function EvidenceList({records,onView}:{records:Evidence[];onView:(r:Evidence)=>void}){return records.length?<><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{records.slice(0,4).map((r,i)=><EvidenceCard key={i} r={r} onView={onView}/>)}</div>{records.length>4&&<details className="muted"><summary className="mt-3">View {records.length-4} more supporting records</summary><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{records.slice(4).map((r,i)=><EvidenceCard key={i} r={r} onView={onView}/>)}</div></details>}</>:<p className="muted">No supporting evidence returned for this section.</p>}
const stepTone=(result?:string)=>{const r=(result||'').toLowerCase();if(/fail|error|abandon|declin|cancel/.test(r))return 'bad';if(/success|complete|confirm/.test(r))return 'good';return 'neutral'}
export function Timeline({events,onView}:{events:Evidence[];onView:(r:Evidence)=>void}){
 const groups=Object.groupBy([...events].sort((a,b)=>(a.timestamp||'').localeCompare(b.timestamp||'')),r=>r.session_id||'Unknown session');
 return <div className="space-y-4">{Object.entries(groups).map(([id,rows])=><div key={id} className="card"><p className="mb-4 text-sm font-semibold">Customer {rows![0].customer_id} <span className="font-normal text-slate-400">· {id}</span></p><ol className="space-y-0">{rows!.map((r,i)=>{const tone=stepTone(r.result);return <li key={i} className="relative ml-1 flex gap-4 border-l border-pulse-100 pb-5 pl-6 last:pb-0"><span className={'absolute -left-2.5 top-0 flex h-5 w-5 items-center justify-center rounded-full '+(tone==='bad'?'bg-amber-100 text-amber-700':tone==='good'?'bg-pulse-100 text-pulse-700':'bg-slate-100 text-slate-500')}>{tone==='bad'?<X size={12}/>:tone==='good'?<Check size={12}/>:<Clock size={11}/>}</span><span className="w-12 shrink-0 pt-0.5 text-xs text-slate-400">{new Date(r.timestamp!).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span><div className="pt-0.5"><p className="text-sm font-medium">{r.action}</p><button className="mt-1 inline-flex items-center gap-1 text-xs text-slate-500 hover:text-pulse-700" onClick={()=>onView(r)}>{r.result?.toLowerCase()}{r.error_code&&<span className="ml-1 rounded bg-slate-100 px-1.5 py-0.5 font-mono text-[10px] text-slate-500">{r.error_code}</span>}<ChevronRight size={12}/></button></div></li>})}</ol></div>)}{!events.length&&<p className="muted">No customer journey evidence was returned.</p>}</div>
}
export function Stepper({step}:{step:number}){return <div className="pulse-stepper mb-6 flex gap-5 text-xs">{['Identify gap','Review update','Approve & hand off'].map((s,i)=><span key={s} className={'flex items-center gap-2 '+(i<=step?'text-pulse-700':'text-slate-400')}><span className={'flex h-5 w-5 items-center justify-center rounded-full '+(i<=step?'bg-pulse-100':'bg-slate-100')}>{i<step?<Check size={12}/>:i+1}</span>{s}</span>)}</div>}
export function MarkdownText({text}:{text:string}){
 const inline=(line:string)=>line.split(/(\*\*.*?\*\*)/g).map((part,i)=>part.startsWith('**')?<strong key={i}>{part.slice(2,-2)}</strong>:part);
 return <div className="space-y-2 text-sm leading-7">{text.split('\n').filter(Boolean).map((line,i)=>line.startsWith('#')?<p key={i} className="font-semibold">{inline(line.replace(/^#+\s*/,''))}</p>:<p key={i}>{inline(line.replace(/^[-*] /,'• '))}</p>)}</div>
}
export function Quote({text=''}:{text?:string}){return <><MarkdownText text={short(text,240)}/>{text.length>240&&<details className="mt-3 text-xs text-slate-500"><summary>Read full excerpt</summary><div className="mt-3"><MarkdownText text={text}/></div></details>}</>}
