import {useState} from 'react';
import {ArrowRight,ChevronRight,Lightbulb,Search} from 'lucide-react';
import type {Bootstrap,Health,JobPayload} from './types';
import {short,when} from './components';
import {healthView,investigationPayload,labels,buckets,value,baseline,delta,type Bucket,type Product,type HealthView} from './healthView';

export function HealthDashboard({scan,data,onReview,onKnowledge,launch,busy}:{scan:Health;data:Bootstrap;onReview:(p:Product)=>void;onKnowledge:()=>void;launch:(p:JobPayload)=>void;busy:boolean}){
 const [filter,setFilter]=useState<Bucket|null>(null),[sort,setSort]=useState('attention'),[question,setQuestion]=useState(''),[askProduct,setAskProduct]=useState('');
 const views=scan.report.products.map(p=>healthView(p,scan,data));
 const counts=Object.fromEntries(buckets.map(b=>[b,views.filter(v=>v.bucket===b).length])) as Record<Bucket,number>;
 const shown=views.filter(v=>!filter||v.bucket===filter).sort((a,b)=>sort==='name'?a.p.product_name.localeCompare(b.p.product_name):buckets.indexOf(a.bucket)-buckets.indexOf(b.bucket));
 const incomplete=views.filter(v=>!v.catalogKnown||v.apis.some(a=>a.status==='unknown'));
 return <div className="health-dashboard">
  <section className="health-results" aria-label="Product health results">
   <form className="health-ask" onSubmit={e=>{e.preventDefault();const v=views.find(v=>v.p.product_name===(askProduct||views[0]?.p.product_name));if(v&&question.trim())launch(investigationPayload(v,scan,question.trim()))}}><label htmlFor="health-question">Ask Product Pulse</label><div className="health-search"><Search size={17}/><input id="health-question" placeholder="Ask about a finding in this scan…" value={question} onChange={e=>setQuestion(e.target.value)}/><button className="primary" aria-label="Ask Product Pulse" disabled={busy||!question.trim()||!views.length}><ArrowRight size={17}/></button></div><div className="health-ask-scope"><label htmlFor="ask-product">Investigate for</label><select id="ask-product" value={askProduct||views[0]?.p.product_name||''} onChange={e=>setAskProduct(e.target.value)}>{views.map(v=><option key={v.p.product_name}>{v.p.product_name}</option>)}</select><span>Uses this scan’s timeframe and evidence.</span></div></form>
   <div className="health-summary" aria-label="Product health summary">{buckets.map(b=><button className="health-summary-tile" key={b} data-tone={b} aria-pressed={filter===b} onClick={()=>setFilter(filter===b?null:b)}><span className="health-summary-count">{counts[b]}</span><strong>{labels[b]}</strong></button>)}</div>
   <div className="health-list-heading"><h2>Products ({shown.length})</h2><div className="flex items-center gap-2">{filter&&<button className="link text-xs" onClick={()=>setFilter(null)}>Show all</button>}<label htmlFor="health-sort" className="text-xs text-slate-500">Sort by</label><select id="health-sort" value={sort} onChange={e=>setSort(e.target.value)}><option value="attention">Attention level</option><option value="name">Product name</option></select></div></div>
   <div className="health-product-list">{shown.map(v=><article key={v.p.product_name} className="health-product" data-tone={v.bucket}>
    <div className="health-product-heading"><h3 className="min-w-0 flex-1"><button onClick={()=>onReview(v.p)}>{v.p.product_name}</button></h3><span className="health-status">{labels[v.bucket]}</span><button className="health-open" aria-label={`Review Signals for ${v.p.product_name}`} onClick={()=>onReview(v.p)}><ChevronRight size={20}/></button></div>
    <p className="health-finding" title={v.primaryIssue?.finding||v.p.summary}>{v.primaryIssue&&<strong>Finding on {v.primaryIssue.date}: </strong>}{short(v.primaryIssue?.finding||v.p.summary,160)}</p>
    <div className="health-metrics"><div className="health-metric"><ProductMetricReadings view={v}/></div>
     <div className="health-metric"><p className="health-metric-title">API Health</p><p className="health-api-summary">{v.catalogKnown?`${v.apis.length} dependent APIs`:`${v.apis.length} observed APIs`} · {v.apiSummary}</p>{v.driver?.peak!=null&&Number.isFinite(v.driver.peak)&&<p className="health-baseline">{v.driver.name} · peak error rate {v.driver.peak}%</p>}</div>
     <div className="health-metric"><p className="health-value">{v.complaints.length}</p><p className="health-metric-label">Complaints</p><p className="health-baseline">{v.priorCount==null?'Prior period unavailable':`${v.complaints.length-v.priorCount>=0?'+':''}${v.complaints.length-v.priorCount} vs ${v.priorCount} prior records`}</p></div>
     <div className="health-metric"><p className="health-value">{v.incidents.length}</p><p className="health-metric-label">Incidents</p></div></div>
    <footer className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-slate-200 pt-3" aria-label="Product finding actions"><p className="text-xs text-slate-500">Understand customer impact and contributing factors.</p><div className="flex flex-wrap gap-2"><button className="secondary" onClick={()=>onReview(v.p)}>View details</button><button className="primary" disabled={busy} onClick={()=>launch(investigationPayload(v,scan))}>Investigate finding<ArrowRight size={15}/></button></div></footer>
   </article>)}{!shown.length&&<p className="muted">No products in this status. <button className="link" onClick={()=>setFilter(null)}>Show all products</button></p>}</div>
   <p className="text-xs text-slate-500 mt-3">Latest observed readings in {scan.scope.start} – {scan.scope.end}. Counts and prior comparisons cover returned evidence, which may be incomplete.</p>
  </section>
  <aside className="health-insights" aria-label="Scan insights"><div className="health-insights-title"><Lightbulb size={22}/><h2>Insights from this scan</h2></div>
   <div className="health-insight"><div><h3>{counts.attention} products need attention</h3><p>{counts.attention?'Review current deviations and the related findings.':'No products have an attention status in this scan.'}</p><button className="link" onClick={()=>setFilter('attention')}>Review findings<ArrowRight size={13}/></button></div></div>
   <div className="health-insight"><div><h3>{counts.recovered} recently recovered</h3><p>Recovery applies to the affected metric or API, not every dependency.</p><button className="link" onClick={()=>setFilter('recovered')}>Check recovery evidence<ArrowRight size={13}/></button></div></div>
   <div className="health-insight"><div><h3>{incomplete.length} products have incomplete API coverage</h3><p>Unmeasured dependencies are not classified as healthy.</p>{incomplete[0]&&<button className="link" onClick={()=>onReview(incomplete[0].p)}>Review missing readings<ArrowRight size={13}/></button>}</div></div>
   <button className="link text-xs mt-4" onClick={onKnowledge}>Review Knowledge Health<ArrowRight size={13}/></button>
  </aside>
 </div>;
}

export function ApiHealthDetails({view,onSource}:{view:HealthView;onSource:(r:import('./types').Evidence)=>void}){
 return <section className="space-y-3"><h3 className="font-semibold">Dependent APIs ({view.apis.length})</h3>{!view.catalogKnown&&<p className="muted">Dependency catalog unavailable. This list contains only APIs identified in scan evidence.</p>}{view.apis.map(a=><article className="api-detail" key={a.name}><div className="flex flex-wrap justify-between gap-2"><h4 className="font-semibold text-sm">{a.name}</h4><span className="health-status" data-tone={a.status==='degraded'?'attention':a.status==='recovered'?'recovered':a.status==='healthy'?'healthy':'monitor'}>{a.status==='unknown'?'No readings':a.status==='recovered'?'Recently recovered':a.status==='degraded'?'Degraded':'Healthy'}</span></div><dl className="api-detail-metrics"><div><dt>Error rate</dt><dd>{value(a.error?.latest)}</dd></div><div><dt>Baseline</dt><dd>{baseline(a.error?.latest)}</dd></div><div><dt>Observed degradation</dt><dd>{a.firstBad?`${when(a.firstBad.timestamp)} – ${a.status==='degraded'?'latest reading still degraded':a.lastBad?when(a.lastBad.timestamp):'unknown'}`:'Not observed'}</dd></div><div><dt>Recovery first observed</dt><dd>{a.recovery?when(a.recovery.timestamp):'Not established'}</dd></div></dl><p className="text-xs text-slate-500">Related incidents: {a.incidents.length?a.incidents.map(r=>r.incident_id||'Unnamed incident').join(', '):'None linked by API name in returned evidence'}</p>{a.error?.latest&&<button className="link text-xs mt-2" onClick={()=>onSource(a.error!.latest!)}>View latest reading<ArrowRight size={13}/></button>}</article>)}<details className="muted"><summary>How display statuses are calculated</summary><p>Directional metric deviation is compared with a near-baseline tolerance of 20% of baseline, capped at 2 and floored at 0.1 units (percentage points for rates). Recovery requires a scan finding linked to an earlier degraded reading and a later near-baseline reading in the selected period. Times are observations, not exact outage or restoration times. The agent’s findings remain unchanged.</p></details></section>;
}

const readingDate=(r?:import('./types').Evidence)=>r?.timestamp?new Date(r.timestamp.slice(0,10)+'T12:00:00Z').toLocaleDateString(undefined,{month:'short',day:'numeric',timeZone:'UTC'}):'Date unavailable';
export function ProductMetricReadings({view,onSource}:{view:HealthView;onSource?:(r:import('./types').Evidence)=>void}){
 const latest=view.primary.latest,atIssue=view.atIssue;
 return <div className="product-reading-comparison">
  <p className="health-metric-label">{latest?.metric_name||'Primary product metric unavailable'}</p>
  <div className="product-reading"><p className="health-value">Latest: {value(latest)} <span className="text-xs font-normal text-slate-500">· {readingDate(latest)}</span></p><p className="health-baseline">Baseline {baseline(latest)} {delta(latest)&&`· ${delta(latest)}`}</p>{latest&&onSource&&<button className="link text-xs mt-1" onClick={()=>onSource(latest)}>View latest reading<ArrowRight size={12}/></button>}</div>
  {view.primaryIssue&&<div className="product-reading"><p className="text-xs font-medium">At issue: {value(atIssue)} <span className="font-normal text-slate-500">· {atIssue?readingDate(atIssue):view.primaryIssue.date}</span></p>{atIssue&&<p className="health-baseline">Baseline {baseline(atIssue)} · {delta(atIssue)}</p>}{atIssue&&onSource&&<button className="link text-xs mt-1" onClick={()=>onSource(atIssue)}>View issue reading<ArrowRight size={12}/></button>}</div>}
 </div>;
}
